import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('imBAADAAAEAvKAplAplAioAjUAieArdAivDOEBFTAAAAAxHGBADABJAABFFAAAAAAHAhhg8AAAVkUAAFDTBGBhPiEgkaKhQhNViVJhPPTFhViQDADBbAgiAAADCAAGBGgrACXANwhEAMBLAUBGAlPBDJhfcMZbbCAJgmOLDguAh2DhiBe4MvkAHBNA');
