import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('AIAVABDDPEaFZgkAADJDEAFWAeAx8TBBXBEFRgiFLDLChwg4ZMgvhaURBjdNAAgzjJgkaKUiKUiVJhPPTFhViQDADBbAgiAAADCAAGBGNeCXANwhBfOHGA4Mz9BjfDLUDJASADiSAAOJGZFZDBDh6GAGNA');
